general update

diff --git a/.github/workflows/node.js.yaml b/.github/workflows/node.js.yaml
--- a/.github/workflows/node.js.yaml
+++ b/.github/workflows/node.js.yaml
@@ -9,7 +9,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-24.04
     timeout-minutes: 10
     steps:
       - name: Checkout from GitHub repository
@@ -21,7 +21,26 @@ jobs:
       - name: Install node modules
         run: npm ci
       - name: Build application
-        run: npm run build
+        shell: bash
+        run: |
+          function retry {
+            local n=1
+            local max=3
+            local delay=5
+            while true; do
+              "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                  ((n++))
+                  echo "Command failed. Attempt $n/$max:"
+                  sleep $delay;
+                else
+                  echo "The command has failed after $n attempts."
+                  return 1
+                fi
+              }
+            done
+          }
+          retry npm run build
         env:
           GATSBY_GOOGLE_MAPS_API_KEY: ${{ secrets.GATSBY_GOOGLE_MAPS_API_KEY }}
           GATSBY_GOOGLE_MAPS_MAP_ID: ${{ secrets.GATSBY_GOOGLE_MAPS_MAP_ID }}
